[package]
name = "sos"
version = "0.1.0"
authors = ["WaDelma <delma@del.ma>"]
edition = "2018"

[dependencies]
nom = "5.0.1"
clap = "2.33.0"
unicode-reverse = "1.0.8"

[dependencies.rand]
version = "0.7.2"
features = ["small_rng"]
